Translator.Web/Models/IPlatformRepository.cs
using System.Collections.Generic;

namespace Translator.Web.Models
{
    public interface IPlatformRepository
    {
        IEnumerable<Platform> GetAll();

        Platform GetById(int id);
    }
}

Translator.Web/Models/MockPlatformRepository.cs
using System.Collections.Generic;
using System.Linq;

namespace Translator.Web.Models
{
    public class MockPlatformRepository : IPlatformRepository
    {
        private List<Platform> _platforms;
        public MockPlatformRepository()
        {
            if (_platforms == null)
            {
                InitializePlatforms();
            }
        }
        public void InitializePlatforms()
        {
            _platforms = new List<Platform>
            {
                new Platform { Id = 1, Name = "Windows" },
                new Platform { Id = 2, Name = "Android" },
                new Platform { Id = 3, Name = "iOS" }
            };
        }

        public IEnumerable<Platform> GetAll()
        {
            return _platforms;
        }

        public Platform GetById(int id)
        {
            return _platforms.FirstOrDefault(p => p.Id == id);
        }

    }
}

Translator.Web/Models/Platform.cs
namespace Translator.Web.Models
{
    public class Platform
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
}

Translator.Web/ViewModels/PlatformViewModel.cs
using System.Collections.Generic;
using Translator.Web.Models;

namespace Translator.Web.ViewModels
{
    public class PlatformViewModel
    {
        public string Title { get; set; }
        public List<Platform> Platforms { get; set; }
    }
}

Translator.Web/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;

namespace Translator.Web.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Register()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
    }
}

Translator.Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Translator.Web.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Translator.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Translator.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Translator.Web/Controllers/PlatformController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Translator.Web.Models;
using Translator.Web.ViewModels;

namespace Translator.Web.Controllers
{
    public class PlatformController : Controller
    {
        private readonly IPlatformRepository _platformRepository;
        public PlatformController(IPlatformRepository platformRepository)
        {
            _platformRepository = platformRepository;
        }
        public IActionResult Index()
        {
            var platforms = _platformRepository.GetAll().OrderBy(p => p.Name);
            var platformViewModel = new PlatformViewModel()
            {
                Title = "Welcome to MiTranslator",
                Platforms = platforms.ToList()
            };
            return View(platformViewModel);
        }
    }
}

Translator.Web/Views/Admin/Index.cshtml
@{
    Layout = "_Admin";
}

Translator.Web/Views/Home/Index.cshtml
@{
    Layout = "_LandingPage";
}

<div class="container">
    <div class="split left">
        <h1>Registered Users</h1>
        <a asp-controller="Platform" asp-action="Index" class="button">Sign In</a>
    </div>
    <div class="split right">
        <h1>Guest</h1>
        <a asp-controller="Admin" asp-action="Index" class="button">Sign In</a>
    </div>

</div>

Translator.Web/Views/Platform/Index.cshtml
@model PlatformViewModel

<h2>@Model.Title</h2>
<h3>Platforms</h3>

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="table-responsive">
                <table class="table table-bordered header-color">
                    <tr>
                        <th width="5%">Platform Id</th>
                        <th width="5%">Platform Name</th>
                    </tr>
                    @foreach (var platform in Model.Platforms)
                    {
                        <tr>
                            <td> @platform.Id </td>
                            <td> @platform.Name </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</div>

Translator.Web/Views/Shared/_Admin.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Admin Dashboard</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/content/css/Admin.css" />
</head>

<body>

    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">iVedix</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a asp-controller="Admin" asp-action="Index">Dashboard</a></li>
                    <li><a asp-controller="Admin" asp-action="Index">Translate</a></li>
                    <li><a asp-controller="Admin" asp-action="Index">Values</a></li>
                    <li><a asp-controller="Admin" asp-action="Index">Keys</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a asp-controller="Admin" asp-action="Index">Welcome, Daniya</a></li>
                    <li><a asp-controller="Admin" asp-action="Index">Logout</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

    <header id="header">
        <div class="container">
            <div class="row">
                <div class="col-md-10">
                    <h1><span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Dashboard <small> Admin Dashboard</small></h1>
                </div>
                <div class="col-md-2">
                    <div class="dropdown settings">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            Settings
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <li id="language"><a asp-controller="Platform" asp-action="Index"> Language</a></li>
                            <li id="platform"><a asp-controller="Home" asp-action="Index"> platform</a></li>
                            <li id="filegroup"><a asp-controller="Home" asp-action="Index"> FileGroup</a></li>
                            <li id="inapp"><a asp-controller="Home" asp-action="Index"> InApp</a></li>
                            <li class="divider"></li>
                            <li id="windows"><a asp-controller="Home" asp-action="Index"> Download for Windows</a></li>
                            <li id="android"><a asp-controller="Home" asp-action="Index"> Download for Android</a></li>
                            <li id="ios"><a asp-controller="Home" asp-action="Index"> Download for iOS</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <section id="breadcrumb">
        <div class="container">
            <ol class="breadcrumb">
                <li class="active">Dashboard</li>
            </ol>
        </div>
    </section>
    <section id="main">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <div class="list-group">
                        <a href="#" class="list-group-item active main-color-bg">
                            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>Dashboard
                        </a>
                        <a href="#" class="list-group-item"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>Platform</a>
                        <a href="#" class="list-group-item"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>Language</a>
                        <a href="#" class="list-group-item"><span class="glyphicon glyphicon-file" aria-hidden="true"></span>FileGroup</a>
                    </div>
                </div>
                <div class="col-md-9">

                </div>
            </div>
        </div>
    </section>


    <div class="container body-content">
        <div class="row">
            @RenderBody()
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.js" type="text/javascript"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
</body>
</html>

Translator.Web/Views/Shared/_LandingPage.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="~/content/css/LandingPage.css" />
</head>
<body>
    @RenderBody()

    <script src="~/content/js/main.js" type="text/javascript"></script>
</body>
</html>

Translator.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/content/css/Site.css" />

</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li><a asp-controller="Home" asp-action="Index"> Home</a></li>
                    <li><a asp-controller="Platform" asp-action="Index"> Platform</a></li>
                    <li><a> Translation</a></li>

                    <li id="settings" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            Settings<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li id="language"><a asp-controller="Platform" asp-action="Index"> Language</a></li>
                            <li id="platform"><a asp-controller="Home" asp-action="Index"> platform</a></li>
                            <li id="filegroup"><a asp-controller="Home" asp-action="Index"> FileGroup</a></li>
                            <li id="inapp"><a asp-controller="Home" asp-action="Index"> InApp</a></li>
                            <li class="divider"></li>
                            <li id="windows"><a asp-controller="Home" asp-action="Index"> Download for Windows</a></li>
                            <li id="android"><a asp-controller="Home" asp-action="Index"> Download for Android</a></li>
                            <li id="ios"><a asp-controller="Home" asp-action="Index"> Download for iOS</a></li>
                        </ul>
                    </li>

                    <li><button type="submit" class="btn btn-warning navbar-btn">Windows</button></li>
                    <li><button type="submit" class="btn btn-warning navbar-btn">Android</button></li>
                    <li><button type="submit" class="btn btn-warning navbar-btn">iOS</button></li>

                    <li>
                        <form class="navbar-form" role="search">
                            <div class="input-group search-box">
                                <input class="form-control" placeholder="Search" name="srch-term" id="srch-term" type="text">
                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </form>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li><a>Register</a></li>
                    <li><a>Log in</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        <div class="row">
            @RenderBody()
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.js" type="text/javascript"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/lib/bootstrap/js/tab.js" type="text/javascript"></script>
</body>
</html>